In [1]:
# Import Libraries
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import tree, metrics
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report


from tqdm import tqdm
import numpy as np
import os
import pandas as pd
!pip install mmh3
!pip install similarity
import mmh3

## Predict ratings

In [101]:
dftrain= pd.read_csv('train_minhash_vectors.csv')
dftrain.rename(columns = {'0':'Rating'}, inplace = True)

# Deal with Rating
dftrain['Rating_1'] = [1 if x == 1 else 0 for x in dftrain['Rating']]
dftrain['Rating_2'] = [1 if x == 2 else 0 for x in dftrain['Rating']]
dftrain['Rating_3'] = [1 if x == 3 else 0 for x in dftrain['Rating']]
dftrain['Rating_4'] = [1 if x == 4 else 0 for x in dftrain['Rating']]
dftrain['Rating_5'] = [1 if x == 5 else 0 for x in dftrain['Rating']]



dftrain=dftrain.head(50000)

In [102]:
dftrain

,Rating,1,2,3,4,5,6,7,8,9,...,96,97,98,99,100,Rating_1,Rating_2,Rating_3,Rating_4,Rating_5
0,2,22064034,21343274,37203318,13197648,6800153,30348788,65281230,14345210,78216434,...,28101636,84868745,28544033,21585836,56101058,0,1,0,0,0
1,2,17093249,5095475,24632176,32325485,5071738,2614467,10024639,728712,558060,...,168656,736531,2455033,16553873,62079021,0,1,0,0,0
2,3,273329258,64202043,11889037,167855076,587490481,407743916,160182324,293175117,686004487,...,381331262,301177564,213205755,489672691,243187887,0,0,1,0,0
3,4,50683715,28705016,117521084,77585501,16830118,56795477,87039799,98233119,105189475,...,155999228,105545685,39522778,69110996,128910029,0,0,0,1,0
4,1,24220675,7536146,9730420,8836384,21666280,9702772,3606038,9481929,23686372,...,16076538,7316285,64598444,20888564,4329615,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,5,919435,24149010,7241121,22415305,9399232,626006,3784806,1130635,22388017,...,4170753,2651087,17567978,6366895,15136335,0,0,0,0,1
49996,3,7612066,38161742,79718825,120221699,53407017,22357051,1714105,3916340,37118483,...,38652922,58617760,30546518,3286736,31168963,0,0,1,0,0
49997,5,1205561,272819029,22282420,188959203,506985326,7838732,620331689,14906805,332710058,...,261614579,177376467,76957616,102586160,2974042,0,0,0,0,1
49998,5,31313846,24149010,38052626,143144092,45159995,21162821,7442590,50144218,56917035,...,105547811,21247978,13494490,31240572,186175012,0,0,0,0,1
49999,1,606315760,287180447,39933164,318834110,44360741,186598579,623644747,457914400,79821234,...,157399547,252021214,131040698,686472052,847515176,1,0,0,0,0

In [103]:
dftest= pd.read_csv('test_minhash_vectors.csv')
dftest.rename(columns = {'0':'Rating'}, inplace = True)


dftest['Rating_1'] = [1 if x == 1 else 0 for x in dftest['Rating']]
dftest['Rating_2'] = [1 if x == 2 else 0 for x in dftest['Rating']]
dftest['Rating_3'] = [1 if x == 3 else 0 for x in dftest['Rating']]
dftest['Rating_4'] = [1 if x == 4 else 0 for x in dftest['Rating']]
dftest['Rating_5'] = [1 if x == 5 else 0 for x in dftest['Rating']]



dftest=dftest.head(10000)

In [104]:
X = dftrain.drop(['Rating', 'Rating_1','Rating_2','Rating_3','Rating_4', 'Rating_5'], axis=1)
y = dftrain[['Rating_1','Rating_2','Rating_3','Rating_4', 'Rating_5']]

Xt = dftest.drop(['Rating', 'Rating_1','Rating_2','Rating_3','Rating_4', 'Rating_5'], axis=1)
yt = dftest[['Rating_1','Rating_2','Rating_3','Rating_4', 'Rating_5']]

In [105]:

# Create a train-test split of these variables
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=42)

X_train=X
X_test=Xt
y_train=y
y_test=yt

## KNN

In [106]:
# Import Library
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import RadiusNeighborsClassifier

# KNN
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train) #values.ravel()



# Training Accuracy
y_pred_train = knn_model.predict(X_train) 
print("Accuracy of Training Data:", accuracy_score(y_train, y_pred_train))


# Testing Accuracy
y_pred = knn_model.predict(X_test)
print("Accuracy of Testing Data:", accuracy_score(y_test, y_pred))



y_pred_train

Accuracy of Training Data: 0.20632
Accuracy of Testing Data: 0.0757

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       ...,
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0]], dtype=int64)

In [107]:
y_pred_train.shape

(50000, 5)

## LogREG

In [156]:
# Logistic Regression
log_model = LogisticRegression(class_weight='balanced', solver = "lbfgs", C = 0.01)
log_model.fit(X_train, np.argmax(y_train.to_numpy(), axis = 1))
# Training Accuracy
y_pred_train = log_model.predict(X_train)
print("Accuracy of Training Data:", accuracy_score(np.argmax(y_train.to_numpy(), axis = 1), y_pred_train))

# Testing Accuracy
y_pred = log_model.predict(X_test)
print(classification_report(np.argmax(y_test.to_numpy(), axis = 1),y_pred))
print("Accuracy of Testing Data:",metrics.accuracy_score(np.argmax(y_test.to_numpy(), axis = 1), y_pred))

Accuracy of Training Data: 0.23248
              precision    recall  f1-score   support

           0       0.22      0.27      0.24      1990
           1       0.17      0.13      0.14      1998
           2       0.24      0.10      0.14      1970
           3       0.21      0.16      0.18      2033
           4       0.22      0.43      0.29      2009

    accuracy                           0.22     10000
   macro avg       0.21      0.21      0.20     10000
weighted avg       0.21      0.22      0.20     10000

Accuracy of Testing Data: 0.2153

## Naive Bias

In [27]:
# Import Libraries
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB

# Gaussain NB
gnb_model = GaussianNB()
gnb_model.fit(X_train, np.argmax(y_train.to_numpy(), axis = 1))

# Training Accuracy
y_pred_train = gnb_model.predict(X_train)
print("Accuracy of Training Data:", accuracy_score(np.argmax(y_train.to_numpy(), axis = 1), y_pred_train))

# Testing Accuracy
y_pred = gnb_model.predict(X_test)
print("Accuracy of Testing Data:",metrics.accuracy_score(np.argmax(y_test.to_numpy(), axis = 1), y_pred))

# Multinomial NB
mnb_model = MultinomialNB()
mnb_model.fit(X_train, np.argmax(y_train.to_numpy(), axis = 1))

# Training Accuracy
y_pred_train = mnb_model.predict(X_train)
print("Accuracy of Training Data:", accuracy_score(np.argmax(y_train.to_numpy(), axis = 1), y_pred_train))

# Testing Accuracy
y_pred = mnb_model.predict(X_test)
print("Accuracy of Testing Data:",metrics.accuracy_score(np.argmax(y_test.to_numpy(), axis = 1), y_pred))

Accuracy of Training Data: 0.21526
Accuracy of Testing Data: 0.2259
Accuracy of Training Data: 0.23162
Accuracy of Testing Data: 0.2134

## Random forest classifier

In [26]:
# Import Libraries
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# Random forest Classifier
rf_model = RandomForestClassifier(n_estimators=1000, class_weight='balanced', random_state=10)
rf_model.fit(X_train, y_train)

# Training Accuracy
y_pred_train = rf_model.predict(X_train)
print("Accuracy of training Data:", accuracy_score(y_train.values.argmax(axis = 1), y_pred_train.argmax(axis = 1)))

# Testing Accuracy
y_pred = rf_model.predict(X_test)
print("Accuracy of Testing Data:", accuracy_score(y_test.values.argmax(axis = 1), y_pred.argmax(axis = 1)))

Accuracy of training Data: 0.94564
Accuracy of Testing Data: 0.2045

## Jaccard Similarity

In [207]:
from sklearn.metrics.pairwise import pairwise_distances
jac_sim = 1 - pairwise_distances(sas.T, metric = "hamming")
# optionally convert it to a DataFrame
jac_sim = pd.DataFrame(jac_sim, index=sas.columns, columns=sas.columns)

In [208]:
jac_sim

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [152]:
xaaa.sort_values(by='1', ascending=False)

,1,2,3,4,5,6,7,8,9,10,...,91,92,93,94,95,96,97,98,99,100
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
74,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
73,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
72,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [209]:
jac_sim.loc['64']['1']

0.0

def jaccard(doc1, doc2, signatures_dict, ):
    signatures_doc1 = np.array(signatures_dict[doc1])
    signatures_doc2 = np.array(signatures_dict[doc2])
    #print(signatures_doc1,signatures_doc2)
    return len(np.argwhere(signatures_doc1==signatures_doc2).flatten())/len(signatures_doc1)
    #return len(np.intersect1d(signatures_doc1, signatures_doc2))/len(np.union1d(signatures_doc1, signatures_doc2))

#import numpy as np
from scipy.stats import mode
 
#Euclidean Distance
def eucledian(p1,p2):
    dist = np.sqrt(np.sum((p1-p2)**2))
    return dist
 
#Function to calculate KNN
def predict(x_train, y , x_input, k):
    op_labels = []
     
    #Loop through the Datapoints to be classified
    for item in x_input: 
         
        #Array to store distances
        point_dist = []
         
        #Loop through each training Data
        for j in range(len(x_train)): 
            distances = eucledian(np.array(x_train[j,:]) , item) 
            #Calculating the distance
            point_dist.append(distances) 
        point_dist = np.array(point_dist) 
         
        #Sorting the array while preserving the index
        #Keeping the first K datapoints
        dist = np.argsort(point_dist)[:k] 
         
        #Labels of the K datapoints from above
        labels = y[dist]
         
        #Majority voting
        lab = mode(labels) 
        lab = lab.mode[0]
        op_labels.append(lab)
 
    return op_labels